### ISSUE TITLE
Implement confirm password field for new users

### ISSUE THREAD

**Issue by phil-davis** [owncloud/user_management#147]
Like in core https://github.com/owncloud/core/issues/29901 where we now have a "retype password" field when a user has been sent an email with a password reset link. (core PR https://github.com/owncloud/core/pull/30981 has the core code)

Do similar for when the administrator creates a new user with just a username and email address. The link in the email should be a page that asks for the password to be typed twice.

**Comment by sharidas** [comment]
I think where ever we deal with password reset, it should be entered twice. Will bring consistancy to our UI. Totally agree with you.

**Comment by phil-davis** [comment]
I am doing this straight away, because acceptance tests were trying to drive this "new user" password setting case just the same as the "reset password" case. PR coming in a moment...

**Comment by phil-davis** [comment]
See PR #146 for implementation.
