### ISSUE TITLE
trying to list users of a groups with a space yields empty list

### ISSUE THREAD

**Issue by butonic** [owncloud/user_management#19]
because the gid us url encoded and ` ` becomes `%20` not `+`

**Comment by phil-davis** [comment]
works for me - see comments https://github.com/owncloud/core/pull/31109#issuecomment-380850660

**Comment by phil-davis** [comment]
Tested just now with current core master and user_management master, after merge of the various fixes.
All weird group names get their members listed OK, like:
```
a space
a#hash
a&and
a/slash
a?question
a|verticalbar
a,comma
a:colon
a=b
```
