### ISSUE TITLE
Read-only option for external storages

### ISSUE THREAD

**Issue by TJHeeringa** [owncloud/user_management#23]
### Steps to reproduce
1. Signin as Admin
2. Go to `User`
3. Add Group `A` (Group that works in the share)
4. Add Group `B` (Group that supervises group `A`, but cannot edit work)
5. Go to `Settings`
6. Go to `Storage`
7. Create external storage for folder `folder` called `folder`
8. Assign group `A` to `folder`
9. Create external storage for folder `folder` called  `folder_readonly`
10. Assign group `B` to `folder_readonly`
11. Conclude `folder_readonly` cannot be made `read_only`

### Expected behaviour
Read-only option for external shares

### Actual behaviour
No read-only option for external shares

### To Do
-  [ ] Create a button in the settings menu of the external storages, next to `enable previews` and `enable sharing`.  

### Server configuration
**Operating system**:
Ubuntu 16.04
**Web server:**
Nginx
**Database:**
MySql
**PHP version:**
7.1.2
**ownCloud version:** (see ownCloud admin page)
10.7
**Updated from an older ownCloud or fresh install:**
Updated
**Where did you install ownCloud from:**
ownCloud repo
**Signing status (ownCloud 9.0 and above):**
Admin

### Client configuration
**Browser:**
Firefox Quantum
**Operating system:**
Windows 10

**Comment by DeepDiver1975** [comment]
@pmaier1 feature request

**Comment by PVince81** [comment]
duplicate of https://github.com/owncloud/core/issues/29873
