### ISSUE TITLE
webUI acceptance tests for quota are failing a lot

### ISSUE THREAD

**Issue by phil-davis** [owncloud/user_management#73]
Somehow it has only started failing a lot in the last day or 2?

e.g. PR #72 
```
--- Failed scenarios:

    /var/www/owncloud/apps/user_management/tests/acceptance/features/webUIManageQuota/manageUserQuota.feature:45
    /var/www/owncloud/apps/user_management/tests/acceptance/features/webUIManageQuota/manageUserQuota.feature:46
    /var/www/owncloud/apps/user_management/tests/acceptance/features/webUIManageQuota/manageUserQuota.feature:47
    /var/www/owncloud/apps/user_management/tests/acceptance/features/webUIManageQuota/manageUserQuota.feature:48
    /var/www/owncloud/apps/user_management/tests/acceptance/features/webUIManageQuota/manageUserQuota.feature:49
/var/www/owncloud/apps/user_management/tests/acceptance/features/webUIManageQuota/manageUserQuota.feature:50
```

But the code and tests in core ``stable10`` seems fine.

Needs investigation.

**Comment by phil-davis** [comment]
@paurakhsharma some of these have been failing in your PRs today, so it has become quite annoying.

Please have a look. Maybe there is some difference from what is in core stable10, that makes the tests here not reliable.

**Comment by paurakhsharma** [comment]
@phil-davis I am unable to reproduce this on my local machine. I ran the failing test in a loop for 40 times but was unable to reproduce it.

**Comment by phil-davis** [comment]
This should be fixed.
