### ISSUE TITLE
Review skipped test scenarios for out-of-date passwords

### ISSUE THREAD

**Issue by phil-davis** [owncloud/user_management#97]
There are some skipped test scenarios that look like they are using out-of-date password substitutions.
e.g. https://github.com/owncloud/user_management/blob/master/tests/acceptance/features/webUIManageUsersGroups/disableUsers.feature#L21
```
And the user logs in with username "user2" and password "%regular%" using the webUI
```
and other uses of ``%regular%`` in the test scenarios.

- [x] review user_management test scenarios for out-of-date passwords and fix #102
- [x] check in core ``stable10`` to see if the problem also exists there https://github.com/owncloud/core/pull/33525
- [x] see if any skipped test scenarios can now pass (in case some bugs have been fixed) - (No, skipped scenarios seems to be passing.)

**Comment by individual-it** [comment]
for master the changes are made in https://github.com/owncloud/user_management/pull/102
